"""Initial migration

Revision ID: daffa9987175
Revises: ffab7ebb3131
Create Date: 2025-04-15 22:00:55.050998+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daffa9987175'
down_revision: Union[str, None] = 'ffab7ebb3131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('muscle_groups', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('workouts', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'description')
    op.drop_column('exercises', 'muscle_groups')
    # ### end Alembic commands ###
