"""описание изменений

Revision ID: 93cd52b5b10b
Revises: 1411bafb1279
Create Date: 2025-04-22 21:22:39.033914+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93cd52b5b10b'
down_revision: Union[str, None] = '1411bafb1279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('exercises', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workout_exercises', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_exercises', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_sets', 'workout_exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workout_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workout_types', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workouts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workouts', 'workout_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workouts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workouts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'workout_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workout_types', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workout_sets', 'workout_exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_exercises', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_exercises', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercises', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
